language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

matrix:
  fast_finish: true
  include:
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.12.x
    env: GO111MODULE=on

install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else go get -t -v ./...; fi
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - nvm install 13.7.0
  - npm install -g snyk

script:
  - go test -v -covermode=atomic -coverprofile=coverage.out
  - snyk test

after_success:
  - bash <(curl -s https://codecov.io/bash)